// Professional framing for the booth demonstration; does not change quiz scoring.
export const workContexts:Record<string,{label:string;tasks:string[];value:string}>={
 data_analyst:{label:'Аналитик данных',tasks:['Находить причины изменений в показателях','Проверять качество данных и гипотезы','Объяснять выводы тем, кто принимает решения'],value:'Понятно, что изменилось, почему это произошло и какое решение стоит проверить. Команда получает аргументированный вывод с проверяемыми данными.'},
 data_scientist:{label:'Исследователь данных',tasks:['Выявлять закономерности и строить прогнозы','Сравнивать модели с простым исходным решением','Оценивать ошибки и границы применимости'],value:'Прогноз или модель, чья польза проверена на новых данных. Команда понимает, когда на результат можно опираться, а когда нужны дополнительные проверки.'},
 ml_engineer:{label:'Инженер машинного обучения',tasks:['Встраивать модели в рабочие приложения','Обеспечивать скорость и устойчивость сервиса','Контролировать качество после запуска'],value:'Модель работает как надёжный сервис: отвечает вовремя, ошибки заметны, обновления можно проверить и при необходимости откатить.'},
 automation_engineer:{label:'Инженер автоматизации',tasks:['Убирать повторяющиеся ручные операции','Связывать системы в единый процесс','Обрабатывать сбои и повторные события'],value:'Повторяющийся процесс проходит без ручного переноса данных. Исключения видны, а повторная обработка не создаёт дубликаты.'},
 bi_developer:{label:'Разработчик бизнес-аналитики',tasks:['Согласовывать смысл показателей','Объединять источники и обновлять данные','Давать команде единую картину бизнеса'],value:'Единая система показателей с понятными определениями и актуальными данными. За каждой цифрой можно проследить расчёт и источник.'},
 product_analyst:{label:'Продуктовый аналитик',tasks:['Находить потери в пути пользователя','Выбирать изменения и измеримый критерий успеха','Проверять эффект продуктовых решений'],value:'Понятно, где продукт теряет пользователей и какое изменение стоит проверить. Решение оценивают по его эффекту, а не только по мнению команды.'},
 software_engineer:{label:'Разработчик программного обеспечения',tasks:['Превращать рабочую задачу в функцию продукта','Проектировать данные и поведение системы','Проверять сложные случаи и исправлять ошибки'],value:'Рабочая функция с понятным поведением, проверками и обработкой ошибок. Её можно поддерживать и развивать вместе с продуктом.'},
 product_designer:{label:'Дизайнер цифровых продуктов',tasks:['Понимать затруднения пользователей','Проектировать понятные сценарии взаимодействия','Проверять решения на реальных действиях людей'],value:'Человеку понятен следующий шаг, а сложный процесс требует меньше усилий. Решение проверено наблюдением за тем, как люди им пользуются.'},
};
export const taskPreviews = [
 [{title:'Путь покупателя',steps:['Товар','Корзина','Оплата']},{title:'Причина в цифрах',steps:['Цена','Товары','Данные']},{title:'Опыт покупателя',steps:['Человек','Оформление','Затруднение']},{title:'Работа оплаты',steps:['Платёж','Проверка','Исправление']}],
 [{title:'Единый экран',steps:['Таблицы','Показатели','Обновление']},{title:'Без ручного сбора',steps:['Сбор','Отправка','Контроль сбоев']},{title:'Объяснение изменений',steps:['Цифры','Проверка','Причина']},{title:'Прогноз спроса',steps:['Прошлое','Модель','Следующая неделя']}],
 [{title:'Точность распознавания',steps:['Обращения','Темы','Ошибки']},{title:'Надёжная модель',steps:['Запрос','Модель','Быстрый ответ']},{title:'Рабочее приложение',steps:['Обращение','Хранение','Обработка']},{title:'Связанные системы',steps:['Почта','Таблица','Уведомление']}],
 [{title:'Понять человека',steps:['Наблюдение','Затруднение','Причина']},{title:'Проверить пользу',steps:['Изменение','Показатель','Эффект']},{title:'Общие определения',steps:['Источники','Правила','Показатели']},{title:'Найти закономерность',steps:['Периоды','Сравнение','Слабое место']}],
 [{title:'Ошибки прогноза',steps:['Примеры','Простое правило','Сравнение']},{title:'Проверка нагрузки',steps:['Поток запросов','Модель','Скорость']},{title:'Понятная ошибка',steps:['Сообщение','Человек','Следующий шаг']},{title:'Польза изменения',steps:['До','Изменение','После']}],
 [{title:'Единый расчёт',steps:['Таблицы','Общее правило','Показатель']},{title:'Точнее прогноз',steps:['Модель','Изменение','Проверка']},{title:'Процесс без рутины',steps:['Заявка','Обработка','Контроль']},{title:'Надёжная функция',steps:['Код','Сложный случай','Тест']}],
 [{title:'План улучшения',steps:['Путь','Гипотеза','Проверка']},{title:'Проверенный прототип',steps:['Макет','Пользователи','Выводы']},{title:'Объяснение в данных',steps:['Изменение','График','Причина']},{title:'Модель в приложении',steps:['Запрос','Ответ','Контроль']}],
 [{title:'Цифрам можно доверять',steps:['Источник','Расчёт','Общий экран']},{title:'Рутина исчезла',steps:['Событие','Автоматизация','Результат']},{title:'Функция устойчива',steps:['Действие','Проверка','Верный результат']},{title:'Качество под контролем',steps:['Модель','Приложение','Наблюдение']}],
] as const;

export const englishWorkContexts: typeof workContexts = {
 data_analyst:{label:'Data Analyst',tasks:['Find the causes of changes in metrics','Check data quality and hypotheses','Explain findings to decision makers'],value:'The team understands what changed, why, and which decision to test, with evidence it can verify.'},
 data_scientist:{label:'Data Scientist',tasks:['Find patterns and build forecasts','Compare models with a simple baseline','Evaluate errors and limits'],value:'A forecast tested on unseen data, with a clear understanding of when the team can rely on it.'},
 ml_engineer:{label:'Machine Learning Engineer',tasks:['Integrate models into working applications','Keep the service fast and reliable','Monitor quality after launch'],value:'A reliable model service with visible failures, tested updates and a way to roll back.'},
 automation_engineer:{label:'Automation Engineer',tasks:['Remove repetitive manual steps','Connect systems into one workflow','Handle failures and repeated events'],value:'A process that runs without manual data transfer. Exceptions are visible and retries do not create duplicates.'},
 bi_developer:{label:'Business Intelligence Developer',tasks:['Agree on what each metric means','Connect and refresh data sources','Give the team a shared view of the business'],value:'Consistent, current metrics with clear definitions. Every number can be traced to its calculation and source.'},
 product_analyst:{label:'Product Analyst',tasks:['Find drop-offs in the user journey','Choose changes and measurable success criteria','Test the effect of product decisions'],value:'The team knows where users drop off and which change to test. Decisions are judged by their effect.'},
 software_engineer:{label:'Software Engineer',tasks:['Turn a work problem into a product feature','Design data and system behavior','Test edge cases and fix errors'],value:'A working feature with predictable behavior, tests and error handling that the team can maintain and develop.'},
 product_designer:{label:'Product Designer',tasks:['Understand where users struggle','Design clear interaction flows','Test solutions with real user actions'],value:'The next step is clear and a complex task takes less effort, verified by watching people use the solution.'},
};
export const englishTaskPreviews = [
 [{title:'Customer journey',steps:['Product','Basket','Payment']},{title:'The numbers behind it',steps:['Price','Products','Data']},{title:'Customer experience',steps:['Person','Checkout','Difficulty']},{title:'Payment reliability',steps:['Payment','Check','Fix']}],
 [{title:'One shared view',steps:['Tables','Metrics','Refresh']},{title:'No manual collection',steps:['Collect','Send','Check failures']},{title:'Explain the change',steps:['Numbers','Check','Cause']},{title:'Forecast demand',steps:['Past','Model','Next week']}],
 [{title:'Recognition accuracy',steps:['Requests','Topics','Errors']},{title:'A reliable model',steps:['Request','Model','Fast response']},{title:'A working application',steps:['Request','Storage','Processing']},{title:'Connected systems',steps:['Email','Table','Notification']}],
 [{title:'Understand the person',steps:['Observe','Difficulty','Cause']},{title:'Test the benefit',steps:['Change','Metric','Effect']},{title:'Shared definitions',steps:['Sources','Rules','Metrics']},{title:'Find a pattern',steps:['Periods','Compare','Weak point']}],
 [{title:'Prediction errors',steps:['Examples','Baseline','Compare']},{title:'Load testing',steps:['Requests','Model','Speed']},{title:'A clear error message',steps:['Message','Person','Next step']},{title:'Value of a change',steps:['Before','Change','After']}],
 [{title:'One calculation',steps:['Tables','Shared rule','Metric']},{title:'A better forecast',steps:['Model','Change','Test']},{title:'Less routine work',steps:['Request','Processing','Checks']},{title:'A reliable function',steps:['Code','Edge case','Test']}],
 [{title:'An improvement plan',steps:['Journey','Hypothesis','Test']},{title:'A tested prototype',steps:['Prototype','Users','Findings']},{title:'An explanation in data',steps:['Change','Chart','Cause']},{title:'A model in an app',steps:['Request','Response','Checks']}],
 [{title:'Numbers you can trust',steps:['Source','Calculation','Shared view']},{title:'Routine work disappears',steps:['Event','Automation','Result']},{title:'A resilient feature',steps:['Action','Check','Correct result']},{title:'Quality under control',steps:['Model','Application','Monitoring']}],
] as const;
