"use client";
import {useEffect,useRef,useState,type FormEvent} from "react";
import { Download, Lock, LogOut, Refresh, ArrowLeft } from "@/components/icons";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from "@/components/ui/table";
import {Header} from "../shell";
import {profiles,intents,interestLabels,legacyProfileNames} from "@/lib/quiz";
type Lead={name:string;company:string|null;contact:string;interest:string;consented_at:string;consent_version:string;profile:string;intent:string};
export default function Operator(){const [pin,setPin]=useState(""),[leads,setLeads]=useState<Lead[]|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);const activity=useRef(0),generation=useRef(0);
 function lock(){generation.current++;setPin("");setLeads(null);setError("");setBusy(false)}
 useEffect(()=>{activity.current=Date.now();const touch=()=>activity.current=Date.now();window.addEventListener("pointerdown",touch);window.addEventListener("keydown",touch);const timer=setInterval(()=>{if(leads&&Date.now()-activity.current>180000)lock()},1000);return()=>{clearInterval(timer);window.removeEventListener("pointerdown",touch);window.removeEventListener("keydown",touch)}},[leads]);
 async function load(e?:FormEvent){e?.preventDefault();if(busy)return;const run=generation.current;setBusy(true);setError("");try{const r=await fetch("/api/operator",{headers:{Authorization:`Bearer ${pin}`},cache:"no-store",signal:AbortSignal.timeout(12000)});const d=await r.json() as {error?:string;leads:Lead[]};if(!r.ok)throw Error(d.error);if(run===generation.current)setLeads(d.leads)}catch(e){if(run===generation.current)setError((e as Error).name==="TimeoutError"?"Нет связи. Попробуйте ещё раз.":(e as Error).message)}finally{if(run===generation.current)setBusy(false)}}
 function exportCsv(){if(!leads)return;const safe=(value:unknown)=>{let s=String(value??"");if(/^[\s]*[=+@\-]/.test(s)||/[\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"'};const rows=[["Имя","Компания","Контакт","Интерес","Профиль","Цель","Согласие UTC","Версия согласия","Источник"],...leads.map(l=>[l.name,l.company,l.contact,interestLabels[l.interest],(profiles.find(p=>p.id===l.profile)?.name||legacyProfileNames[l.profile]||l.profile),intents.find(i=>i.id===l.intent)?.label,l.consented_at,l.consent_version,"Taj-Tech 2026"] )];const blob=new Blob(["\uFEFF"+rows.map(r=>r.map(safe).join(";")).join("\r\n")],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`navtech-contacts-${new Date().toISOString().slice(0,10)}.csv`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <div className="app-shell"><Header/><main className="operator-main"><a href="/" className="return-link"><ArrowLeft size={16}/>К стенду</a><div className="operator-heading"><div><span className="eyebrow mint">Для команды NavTech</span><h1>Контакты стенда.</h1></div><Lock size={44}/></div>{leads===null?<form onSubmit={load} className="operator-login"><label>Код оператора<Input type="password" autoComplete="off" required value={pin} maxLength={100} onChange={e=>setPin(e.target.value)} placeholder="Введите код команды"/></label><Button className="primary-button" disabled={busy}>{busy?"Открываю…":"Открыть контакты"}</Button><p className="fine-print">Открывайте этот экран на устройстве команды. Контакты скрываются после трёх минут бездействия.</p></form>:<><div className="operator-tools"><span>{leads.length} контактов</span><Button variant="outline" onClick={()=>load()} disabled={busy}><Refresh size={16}/>{busy?"Обновляю…":"Обновить"}</Button><Button variant="outline" onClick={exportCsv} disabled={!leads.length}><Download size={16}/>Скачать CSV</Button><Button variant="ghost" onClick={lock}><LogOut size={16}/>Закрыть доступ</Button></div>{leads.length?<div className="leads-table"><Table><TableHeader><TableRow><TableHead>Имя / компания</TableHead><TableHead>Контакт</TableHead><TableHead>Интерес</TableHead><TableHead>Профиль</TableHead><TableHead>Согласие</TableHead></TableRow></TableHeader><TableBody>{leads.map((l,i)=><TableRow key={i}><TableCell><strong>{l.name}</strong><small>{l.company||"—"}</small></TableCell><TableCell>{l.contact}</TableCell><TableCell>{interestLabels[l.interest]}</TableCell><TableCell>{(profiles.find(p=>p.id===l.profile)?.name||legacyProfileNames[l.profile]||l.profile)}</TableCell><TableCell>{new Date(l.consented_at).toLocaleString("ru-RU",{timeZone:"Asia/Dushanbe"})}</TableCell></TableRow>)}</TableBody></Table></div>:<div className="operator-empty">Здесь появятся контакты гостей, которые разрешили связаться с ними. Демо-данные сюда не попадают.</div>}</>}{error&&<p className="inline-error" role="alert">{error}</p>}</main></div>
}
